### ISSUE TITLE
@JsonProperty annotation reads wrong class attribute

### ISSUE THREAD

**Issue by qpi** [appvision-gmbh/json2typescript#110]
I tried to use Angular's FormControl and FormGroup inside my models, but strangely json2typescript do not linked the attribute just after the annotation.
For example I have this implementation:
```
    @JsonProperty("id", String)
    private _id: string = undefined;
    
    public get id(): string {
        return this._id;
    };
    public set id( id: string) {
        this._id = id;
    };
    private _id$: FormControl = new FormControl('', [
        Validators.required,
        Validators.minLength(8),
        Validators.maxLength(15)
    ]);
```
so when I call serialize() method on this model, strangely the result will be like this: { id: FormControl ....... }

I created a live stackblitz example to see the issue and it contains also my light modification to avoid this wrong behaviour. See the console for the result.
https://stackblitz.com/edit/angular-8z7dxm

**Comment by andreas-aeschlimann** [comment]
That is very strange and looks like a bug. Thanks for your submission.

**Comment by andreas-aeschlimann** [comment]
Have you figured out if this is really a bug or some other issue?

**Comment by spoilsportmotors** [comment]
I think you can safely close this; if you update the json2typescript dependency in the provided stackblitz example to current (1.4.1 at this time), the error is gone.

**Comment by andreas-aeschlimann** [comment]
> I think you can safely close this; if you update the json2typescript dependency in the provided stackblitz example to current (1.4.1 at this time), the error is gone. 

Thanks for the heads up!
