### ISSUE TITLE
Can't use exclamation mark with property

### ISSUE THREAD

**Issue by thanhlelgg** [AppVision-GmbH/json2typescript#118]
Hi guys, I have a class with a property that doesn't allowed to be `undefined`. So I tried:
```
    @JsonProperty('segment', String)
    segment!: string;
```
But it's not working, the `segment` will be undefined after deserialized, even it exists in the json file.
It's working fine if I use optional property:
```
    @JsonProperty('segment', String)
    segment?: string = undefined;
```
There's a reason that we can't use the `!`?

Update:
Look like the convert only work if we declare the variable as `undefined`, is there any reason for this? and can we by pass this somehow?
I don't want to check if my value is null or not every time I use it, and I don't want to disable strict non null function neither.

**Comment by andreas-aeschlimann** [comment]
Please assign a value, for example ‘segment!: string = ""‘. Then it will work.

**Comment by thanhlelgg** [comment]
> Please assign a value, for example ‘segment!: string = ""‘. Then it will work.

Well, it could work with string, but I also have some custom type (a class), so I have to create a new instance for it if I don't want to use the `undefined`?

**Comment by andreas-aeschlimann** [comment]
I know it's not perfect. You could use a union type with undefined or null, or you could provide an empty instance.
