### ISSUE TITLE
Object is not extensible error - using ngrx store-freeze

### ISSUE THREAD

**Issue by Myster1o619** [AppVision-GmbH/json2typescript#119]
<b>Error Message:</b><br><hr>
![image](https://user-images.githubusercontent.com/30766852/72323240-e1e13c00-36b0-11ea-8465-75d9b546104e.png)
This is where the code is breaking: <hr>
![json2typescriptBreaking](https://user-images.githubusercontent.com/30766852/72323275-f9b8c000-36b0-11ea-839b-73b618aced7e.PNG) <hr>
I am using store-freeze from ngrx, if I remove store-freeze, I do not get this error. I am breaking reference from the object retrieved from the store using cloneDeep from Lodash. <hr>
*const jsonObj = this.jsonConverter.deserializeObject(jObject, ctor);* <br>
So this jObject that is being used here has been obtained using cloneDeep. <br>
I have also checked this object with Object.isFrozen() - which returns false. <br>
**This is the Object:** <br>
{
"id": "7012cf22-4874-454d-8d9a-12f9e45603dd",
"isDynamicWidget": true,
"pluginID": "0",
"parentID": "",
"pluginKey": "Plugin_Default",
"firstProperty": "this is initialized",
"secondProperty": "0",
"jsonWithType": "json with a type",
"jsonWithoutType": "json without a type",
"jsonWithAnotherName": "json with another name",
"requiredJson": "some required jason",
"styling": {
"spacingTop": 0,
"spacingBottom": 0,
"spacingLeft": 0,
"spacingRight": 0,
"float": 0,
"classes": ""
},
"someObjectItem": {
"propertyOne": "one",
"propertyTwo": 2
},
"objectArrayItems": [
{
"propertyOne": "one",
"propertyTwo": 2
},
{
"propertyOne": "one",
"propertyTwo": 2
}
],
"basicArray": [],
"basicNumberArray": [],
"basicBooleanArray": [],
"basicDateArray": []
}
<br>
Code: <br>
@JsonObject('ObjectClass')
export class ObjectClass {

  constructor(init?: Partial<ObjectClass>) {
    if (init) {
      Object.assign(this, init);
    }
  }

  @TextInput({ label: 'First Property' })
  @JsonProperty('propertyOne')
  propertyOne = 'one';

  @NumberInput({ label: 'Second Property' })
  @JsonProperty('propertyTwo')
  propertyTwo = 2;
}
<br>
Please let me know if you need any additional information. Am I missing something simple regarding this issue I am encountering?

**Comment by andreas-aeschlimann** [comment]
Is this somehow related or could help? https://github.com/brandonroberts/ngrx-store-freeze/issues/39

I haven't worked with ngrx store yet so I am not sure if I can help there.

It looks like once you freeze an object (instance), it may not be manipulated in the way json2typescript does.

**Comment by Myster1o619** [comment]
Thanks for the link.

The **ctor** (classReference / constructor function) in
`const jsonObj = this.jsonConverter.deserializeObject(jObject, ctor);`
appears to be frozen, the **jObject** is not - could that possibly be the cause?

Will investigate further.
Thanks for your help.

**Comment by andreas-aeschlimann** [comment]
Yes, I think so. Unfortunately I do not really know. :-/

**Comment by andreas-aeschlimann** [comment]
@Myster1o619 does this issue still persist in version 1.2.4? I am just asking because we have changed the way that property info is checked and if we are lucky, it fixes your problem.

**Comment by Myster1o619** [comment]
@andreas-aeschlimann - thanks for getting back to me regarding this. <br>
I will test on version 1.2.4 and let you know. <br>
Thanks again.

**Comment by Myster1o619** [comment]
@andreas-aeschlimann 1.2.4 seems to have sorted this issue out. <br>
Thanks for all your help. Will close the issue and re-open if necessary.
