### ISSUE TITLE
Properties of child classes not (de)serialized

### ISSUE THREAD

**Issue by andreas-aeschlimann** [AppVision-GmbH/json2typescript#129]
The documentation should state that since around v1.2.0+, properties of child classes do not work anymore unless the `@JsonObject("ClassName")` is provided. Right now this seems rather optional.

**Comment by tobiasschweizer** [comment]
> Right now this seems rather optional.

If you don't know whether it's optional or not, then no one does ;-)

**Comment by andreas-aeschlimann** [comment]
It is due to the changes in the inheritance handling that were made in https://github.com/AppVision-GmbH/json2typescript/pull/121

So we basically missed a breaking change in the update v1.2.5: The class decorator parameter 1 must not be empty for child classes.

**Comment by tobiasschweizer** [comment]
> It is due to the changes in the inheritance handling that were made in #121
> 
> So we basically missed a breaking change in the update v1.2.5: The class decorator parameter 1 must not be empty for child classes.

Ok, I get it. So then documenting it would be good.

**Comment by andreas-aeschlimann** [comment]
Yes, and I will also force the use of a parameter whenever the `@JsonObject` decorator function is called. Then developers cannot miss bad implementations.
