### ISSUE TITLE
Need to follow semver versioning.

### ISSUE THREAD

**Issue by ericgruss** [AppVision-GmbH/json2typescript#134]
If you make a breaking change you should always update the Major Version number.  Minor version changes should always be non-breaking.  Version should be 2.x.x

**Comment by andreas-aeschlimann** [comment]
I know the theory and we will upgrade to version 2 when the API changes. However, we don't have a real breaking change here.

The documentation already stated before version 1.4 that you should pass a parameter to the @JsonObject. It was a bug that forgot to force developers to pass the parameter.

The package was not working properly between versions 1.2.5 and 1.4 if @JsonObject had 0 parameters with class inheritance. If we didn't throw an error now, some people would never notice that. That is why I decided not to upgrade to version 2 yet.
