### ISSUE TITLE
Not able to convert the Map objects

### ISSUE THREAD

**Issue by luben-gonsalves** [AppVision-GmbH/json2typescript#139]
```
import { JsonObject, JsonProperty } from "json2typescript";
import { Person } from "../Person/Person";
import { OrganisationConnection } from "../../Relationships/OrganisationConnection";

@JsonObject("User")
export class User extends Person {
  @JsonProperty("organisationConnections", Map, true)
  organisationConnections: Map<string, OrganisationConnection> = undefined;
}
```
I am doing a post request , when i try to deserialize the the json to User class it doesnt convert gives me this error

` Fatal error in JsonConvert. Failed to map the JSON object to the class "UserRegistrationRequestBody" because of a type error.

        Class property:
                organisationConnections

        Expected type:
                Map

        JSON property:
                organisationConnections

        JSON type:
                object

        JSON value:
                {"x28d3fad3p0f51p11eap951cp1901ff00d4f5":{"organisationId":"x28d3fad3p0f51p11eap951cp1901ff00d4f5","uhid":"ACH12","connectedById":"x28d3fad3p0f51p11eap951cp1901ff00d4f5","connectedByName":"Dr. Abhishek Malviya","organisationName":"Dr. Abhishek's Clinic"}}

        Reason: Expected type is unknown. There might be multiple reasons for this:
        - You are missing the decorator @JsonObject (for object mapping)
        - You are missing the decorator @JsonConverter (for custom mapping) before your class definition
        - Your given class is undefined in the decorator because of circular dependencies`

**Comment by andreas-aeschlimann** [comment]
Map has not been implemented in the library. You have to convert it to object or array to work with it.

You can use the `@CustomConverter` decorator to make this work, it should not be too hard!

**Comment by luben-gonsalves** [comment]
Okay thank you.

**Comment by luben-gonsalves** [comment]
This was a great library, i wish it had support for Map, because the application i am working on  use Lot of Maps, will it support anytime in future? do you know of any other library which does??

**Comment by andreas-aeschlimann** [comment]
> This was a great library, i wish it had support for Map, because the application i am working on use Lot of Maps, will it support anytime in future? do you know of any other library which does??

I don't know of a library that does support it. But if you use it a lot, you could write some code and we could include it? I honestly don't think it is too hard. A map is nothing else than an object with making all properties optional, right? The problem is maybe the generic part of the map, because it does not exist in the compiled JavaScript.

If you need a quick fix:
1. Do not use Map as the class type, use Organisation[]. Json2typescript will automatically do the mapping properly, even though you have an JSON object and not a json array.
2. If you internally need the Map type, just create a function that converts it. Something like this:

```
@JsonProperty("_organisationConnections", [OrganisationConnection], true)
private _organisationConnections: OrganisationConnection[] = [];

get organisationConnections(): Map<string, OrganisationConnection> {
  const m = new Map<string, OrganisationConnection>();
  for (const o of this._organisationConnections) {
    m.set(o.organisationId, o);
  }
  return m;
}
```

**Comment by luben-gonsalves** [comment]
oh okay thanks alot will try this :).
