### ISSUE TITLE
PropertyMatchingRule not Exported from index.ts?

### ISSUE THREAD

**Issue by tobiasschweizer** [appvision-gmbh/json2typescript#140]
I use version 1.4.1 of `json2typescript` and noticed the following **internal** import path in my code:

`import { PropertyMatchingRule } from "json2typescript/src/json2typescript/json-convert-enums";`

I think `PropertyMatchingRule ` should be added to https://github.com/AppVision-GmbH/json2typescript/blob/ad6a04b729d13988a71313a20457eec95bd24a9c/index.ts#L3

**Comment by andreas-aeschlimann** [comment]
Yes, I have already seen and fixed that. :)

**Comment by andreas-aeschlimann** [comment]
It is here:
https://github.com/AppVision-GmbH/json2typescript/pull/138/commits/bd3725d97bc27bf552aeafc04a530b4714a4b180

**Comment by tobiasschweizer** [comment]
> It is here:
> [bd3725d](https://github.com/AppVision-GmbH/json2typescript/commit/bd3725d97bc27bf552aeafc04a530b4714a4b180)

just tell me once you published a new version containing this fix

**Comment by andreas-aeschlimann** [comment]
This will be included in the 1.5.0 release coming today, @tobiasschweizer
