### ISSUE TITLE
Type 'undefined' is not assignable to type 'string'

### ISSUE THREAD

**Issue by JBuijgers** [appvision-gmbh/json2typescript#141]
Using the [Mapping example](https://www.npmjs.com/package/json2typescript#mapping-example), multiple errors occur. An example would be the name property, it is declared as a string, but it is assigned an undefined value as well. Hence, the error "Type 'undefined' is not assignable to type 'string'". I feel like I missed something in the documentation, help is appreciated.

**Comment by andreas-aeschlimann** [comment]
> Using the [Mapping example](https://www.npmjs.com/package/json2typescript#mapping-example), multiple errors occur. An example would be the name property, it is declared as a string, but it is assigned an undefined value as well. Hence, the error "Type 'undefined' is not assignable to type 'string'". I feel like I missed something in the documentation, help is appreciated.

Hey, when I wrote the docs I used strict mode false (in tsconfig, compiler options). I guess you use strict mode true, then the examples do not work.

If you like you can make a PR to fix the ReadMe. I think it would be cleaner if the example worked in both modes.

**Comment by andreas-aeschlimann** [comment]
To fix it, just assign a default value of the necessary type.

`name: string = undefined`

then befomes

`name: string = „“`

**Comment by JBuijgers** [comment]
Great, thanks for clarifying! I was wondering btw, why is it that a class property needs a default value before a @JsonProperty annotation is able to assign it a value?

**Comment by andreas-aeschlimann** [comment]
Because then the deserializer of JsonConvert couldn't find those properties and they would be ignored. It is some behavior of JavaScript that properties do not "exist" until they have a value.

**Comment by andreas-aeschlimann** [comment]
FYI, I have updated the ReadMe in the latest commit on GitHub.
