### ISSUE TITLE
README: Make Clearer What JSOn Refers to 

### ISSUE THREAD

**Issue by tobiasschweizer** [appvision-gmbh/json2typescript#145]
In the README, it is stated:

> Serializing (TypeScript to JSON)> (any | any[]) serialize(data: any | any[], classReference?: { new(): T })
> Tries to serialize a TypeScript object or array of objects to JSON.
> Tip: The return value is not a string. In case you need a string as result, use JSON.stringify() after calling the serialize method.

Could it be made clearer that JSON refers to a JS object, not a serialised representation of an object (a string)?

**Comment by andreas-aeschlimann** [comment]
After reviewing the docs, I think this should be clear enough. The tip clearly states that the return value is not a string.
