### ISSUE TITLE
Defining HashMap<key:string, <SomeType>> in @JsonProperty annotation

### ISSUE THREAD

**Issue by erhanfirat** [appvision-gmbh/json2typescript#146]
I wonder if there is any way to map data in format HashMap<key:string, <SomeType>> using json2typescript annotations?

I have tried to define an interface for the HashMap as below: 
```

export interface ResponsibilityInterface {
    [key: string]: UserModel;
}

export declare var Responsibility: ResponsibilityInterface;
```

In Model: 

`@JsonProperty('responsibnilities', Responsibility, true)
responsibilities: Responsibility[] = null;`

**Comment by andreas-aeschlimann** [comment]
It is not possible out of the box.

What you want to achieve could be done with a `CustomConvert` implementation. If you can make it work, feel free to share it with us.
