### ISSUE TITLE
Nuxt Client Site Hydration

### ISSUE THREAD

**Issue by speery4** [appvision-gmbh/json2typescript#154]
Our app is using Nuxt for server side rendering and we are having an issue with client side hydration. I have traced the issue back to us renaming props. Server side the model is fine, but when we get to the client the props have already been renamed so when we try to deserialize the object it fails because the property is missing. Outside of passing the entire original object to the client, i'm not sure the best way to handle this would be.

Here is an example:
```
  @JsonProperty('FactBox')
  public factBoxBody?: string = null;
```

Results in this error client side:
```
Fatal error in JsonConvert. Failed to map the JSON object to the class "Product" because the defined JSON property "FactBox" does not exist:
	Class property: 
		factBoxBody
	JSON property: 
		FactBox
```

**Comment by andreas-aeschlimann** [comment]
Sorry for the late reply, I didn't get a notification about your question. Have you solved it by now?

If not, can you show an example json string that you try to deserialize? As the docs state, you can make the property optional like this:

```
  @JsonProperty('FactBox', String, true) // String should be used to make sure you deserialize to string if the property is present
  public factBoxBody: string | null = null; // if you want null, better use union type with null because ? means undefined
```

**Comment by andreas-aeschlimann** [comment]
Closing this issue for now. Please let us know if there are any more issues.
