### ISSUE TITLE
Bug with 4.x typescript versions

### ISSUE THREAD

**Issue by Xavod** [appvision-gmbh/json2typescript#157]
The library does not work with the 4.x typescript versions of a project under Angular 11.x.
No error in eslint in the code, but when trying to deserialize, we get the following error which refers to the @JsonProperty of the model in the browser console :
 it's not a function'.
Has anyone ever encountered this concern and if so, have you found a solution?

Thank you for your feedback

**Comment by andreas-aeschlimann** [comment]
Are you sure about that? I am using TypeScript 4.0.5 with Angular 11 in this very second in a project.

Can you provide an example to rule out any other issues?

**Comment by andreas-aeschlimann** [comment]
Please feel free to reopen the issue, if the problem still persists.
