### ISSUE TITLE
deserialize array

### ISSUE THREAD

**Issue by scinfu** [appvision-gmbh/json2typescript#170]
How can I deserialise an array without use a foreach statement?
json example:
```
[{
'name':'foo',
},{
'name':'bar',
}]
```
```
const jsonConvert: JsonConvert = new JsonConvert();
const users = jsonConvert.deserializeObject(response.data, User[]);
```

User[] is not accepted.

Thank you

**Comment by andreas-aeschlimann** [comment]
Hello and thanks for your issue.

As stated in the docs, you can only use `deserializeObject` to deserialize objects. You should use `deserializeArray` if you are expecting an array or `deserialize` if you expect both.

**Comment by andreas-aeschlimann** [comment]
I am going ahead and close this question. Feel free to report back if you find any bugs.
