### ISSUE TITLE
String deserialization broken in 1.5.0

### ISSUE THREAD

**Issue by ksstoneware** [appvision-gmbh/json2typescript#187]
String deserialization appears to be broken in version 1.5.0 if I set the value to a JSON object. It will deserialize successfully even though the value is not a string.

I have a class like this:
```
@JsonObject("ClientLogMessage")
export class ClientLogMessage extends LogMessage {
    @JsonProperty("code", String)
    @Validator.IsNotEmpty()
    @Validator.IsString()
    public code: string = undefined;
}
```
In a unit test, I set `testData.code = { name: "code" }` and call `converter.deserializeObject(testData, ClientLogMessage);`. In 1.4.1, it throws an error as expected. In 1.5.0, it does not and results in `code` being set as the JSON object.

**Comment by andreas-aeschlimann** [comment]
Thank you again for this issue. 

This was a tricky one because no test existed and it is a rare error. Usually, we just have bad primitive types and not completely different types.

A fix will be published to NPM in the next minutes.

**Comment by ksstoneware** [comment]
@andreas-aeschlimann Happy to help! Thank you for the quick fix!
