### ISSUE TITLE
Feature Request: Workaround for Duplicate Class Names Between Local Code and Dependency

### ISSUE THREAD

**Issue by angad-singh15** [appvision-gmbh/json2typescript#189]
After reading your documentation, I understand that the @JsonObject decorator now requires the class identifier as the first parameter. However, one of my dependencies for my project also uses to Json2Typescript and has a conflicting class name with one of my own. Is there a way I can have Json2Typescript separate the use of the duplicate class names?

Thanks in advance!

**Comment by andreas-aeschlimann** [comment]
I also recommend to encourage the third-party dependency to use unique names for their class identifiers.

If you have something more to add, feel free to reopen the issue.
