### ISSUE TITLE
how to set null property to default value?

### ISSUE THREAD

**Issue by kongmengfei** [appvision-gmbh/json2typescript#196]
I want to deserialize objects and set the default value when the property value is null.

![image](https://user-images.githubusercontent.com/57654821/210469181-cbecac46-8f3c-494a-a76f-6de6117d16d2.png)

below is my code:

![image](https://user-images.githubusercontent.com/57654821/210469248-3c5000bf-5769-4a7c-b6ea-ccb104aaf69f.png)

![image](https://user-images.githubusercontent.com/57654821/210469371-9d449ffc-4f9c-480b-81f5-0220571ed9a4.png)

Can you help me? the demo use js code but my project is ts. 

Thanks

**Comment by andreas-aeschlimann** [comment]
Hello, there are multiple options you can use in the `@JsonProperty` decorator as third parameter.

Please refer to the docs:
https://github.com/appvision-gmbh/json2typescript#property-converting-mode

Most likely, you want `PropertyConvertingMode.IGNORE_NULLABLE`. This means that the mapper is not applied if the property is missing, undefined or null; the property is not added to the result. 

When deserializing, the default TypeScript class property value will survive when it was NULL or missing in the JSON.
