### ISSUE TITLE
typed arrays deserialiZation 

### ISSUE THREAD

**Issue by hshahi** [appvision-gmbh/json2typescript#198]
Hi

I am struggleing to make things work for scenario below 
@jsonobject('MyClass')
class MyClass {
}

@jsonobject('MyClassList')
MyClassList extends Array<MyClass >{
}

can you give me an example how to call jsonconvert.deserialise(json, MyClassList);
json is from httpclient.get()

Please give an example

Thanks
Shahi

**Comment by andreas-aeschlimann** [comment]
The line `MyClassList extends Array` does not make sense to me. You can only use classes with the JsonObject decorator.

If you want to deserialize an array of `MyClass`, please refer to the docs how to do it. You can do it without a `MyClassList` construct.

**Comment by hshahi** [comment]
sorry it is 
@JsonObject('MyClassList')
MyClassList extends Array<MyClass> {
  giveMe3rdItem() {}
}

it is to do with the fact I want to use typesafe collection so that it can have its own methods. I can not use it with
MyClass[] and giveMe3rdItem() has to reside somewhere else. That is the whole point.

**Comment by andreas-aeschlimann** [comment]
Please set up a Stackblitz where you show example JSON string and what you want to achieve when deserializing. Otherwise it is hard to understand.

**Comment by hshahi** [comment]
Hi, It is easy, have a entity class say "student" with name and surname property and then have "StudentList" class that inherit from Array< Student > having applied @jsonobject and @jsonproperty applied to them.

then have a json array of the following 
const jsonString = '
[
  {
    "Name": "Senpai",
    "Surname": "Stevens"
  },
  {
    "Name": "Yui Rio",
    "Surname": "Stevens"
  }
]';

then call 

let jsonConvert: JsonConvert = new JsonConvert();

        try {
            const jsonObject = JSON.parse(jsonString);
            const studentlist = jsonConvert.deserializeObject(jsonObject, StudentList);

        } catch (e) {
            console.log((<Error>e));
        }

**Comment by andreas-aeschlimann** [comment]
Just use `deserializeArray(jsonObject, Student)`. 

If you want to map your json to a StudentList, it will not work out of the box. I think you will need to do some additional work with the `JsonCustomConvert`. You will find some help in the docs how to do it. 

If you need further support, I suggest you to check the docs or consult a platform like StackOverflow.
