### ISSUE TITLE
Fatal error in JsonConvert. You must use unique class identifiers in the @JsonObject() decorator.

### ISSUE THREAD

**Issue by nappalm** [appvision-gmbh/json2typescript#200]
I am having the following error, but I really don't know if it is a json2 problem

the code is the following:
import { JsonObject, JsonProperty } from 'json2typescript';

```
@JsonObject('CalculationModel')
export class CalculationModel {
   @JsonProperty('model', String)
   pattern = '';
 
  .... others json props
```

error:
```
Error: Fatal error in JsonConvert. You must use unique class identifiers in the @JsonObject() decorator.

	Class identifier: 
		CalculationModel

This class identifier has been already used for class "CalculationModel".
```

```
  3 | @JsonObject('CalculationModel')
> 4 | export class CalculationModel {
    |           ^
  5 | @JsonProperty('model', String)
  6 | Model = '';
```

**Comment by andreas-aeschlimann** [comment]
This means that you are importing your classes multiple times. If json2typescript detects that the same class identifier has been imported multiple times, it throws an error. This protects the developer from accidentally copy-pasting the same identifier.

Somebody already opened an issue here I believe. He used some build system/tools that I don't know, but they have provoked this exact error due to multiple imports.

**Comment by nappalm** [comment]
@andreas-aeschlimann  Any recommendations?, in my code there is only that class name. I don't see why this error can occur.

**Comment by andreas-aeschlimann** [comment]
Unfortunately I have no idea. I would try to isolate the issue by starting with a minimal example (json2typescript + classes only) and then add more packages. It is pretty likely that something else causes the issue that is out of our control. As I mentioned, someone else had this issue once.

In theory, you could try a very ugly and hacky workaround like this:

```
let i = 0;

@JsonObject('CalculationModel' + i++)
export class CalculationModel {
```

This would ensure that the class name is unique... But it could possible cause other problems later.

**Comment by nappalm** [comment]
I currently have option 2 in my entire project. It is too strange that in development it triggers this type of error and in production it does not.

**Comment by nappalm** [comment]
It makes no sense, what would happen with this example

```
import { JsonObject, JsonProperty } from 'json2typescript';

import { CalculationModel } from './CalculationModel';

@JsonObject('CalculationResponse')
export class CalculationResponse {
  @JsonProperty('results', [CalculationModel])
  Results: CalculationModel[] = [];

  @JsonProperty('errors', [String])
  Errors: string[] = [];
}
```
CalculationModel is imported to be used in another model, as well as exported for use throughout the application, it should be `src/models/calculationmodel` to be valid for what you mention?

**Comment by andreas-aeschlimann** [comment]
I don't have enough insights how Webpack/Angular handles all these imports. But I could imagine that in production it somehow recognizes after minimation that the imports are the same and merges them. That's maybe why we have the issue only on development. I noticed that I have problems when I use the project path in the import. Instead, I now use only relative paths when importing classes.
